### ISSUE TITLE
Error retrying in 3 seconds

### ISSUE THREAD

**Issue by GitStudying** [supersu-man/SpotifyPlaylistDownloader#2]
I am trying to download the same playlist as in #1. So still 3000+ songs, it does download 17 songs of it. For a lot of songs it flashes error retrying in 3 seconds for a very short time (less than half a second) then it kind of gets stuck on the song until it downloads that one song and then skips over 10 to 50 songs and downloads that one. I will upload a video of it as this might be more useful: https://youtu.be/OoOy-n6zerA.

System info:
OS: Android 11
Device; Samsung A41

**Comment by supersu-man** [comment]
It works on A21s, S9, One plus 7pro and Pixel 3. All of them are on Android 11. I couldn't find a way to reproduce your issue. Maybe it's related to your device. Did you try it on another device?

**Comment by GitStudying** [comment]
Currently I have no other device at hand. In a while I can try it with another device. I will come back to you.

**Comment by GitStudying** [comment]
I now also tried it running in a VM, with Android studio. This gave exactly the same behaviour, the emulated device was Pixel 4a. also the Pixel 3a did have the same behaviour. After a debug it says repeatedly:
W/.supersuman.sp: Accessing hidden field Lcom/android/okhttp/internal/huc/DelegatingHttpsURLConnection;->delegate:Ljava/net/HttpURLConnection; (blacklist, reflection, denied)
    Accessing hidden field Ljava/net/URLConnection;->requests:Lsun/net/www/MessageHeader; (greylist-max-o, reflection, denied).

**Comment by supersu-man** [comment]
Are you building the app from code or trying APK released. Because you need to put your own Spotify API keys if you build the app by your self from the code. The APKs I released have my own Spotify API keys in them.

**Comment by GitStudying** [comment]
I am trying the APK released. Weird that you can't replicate it. The following video is from the emulator: https://youtu.be/j9fQ3jK5EpE.

**Comment by supersu-man** [comment]
Why is that app flashing when you are on home and trying to open files? Is that problem not with you? It's so weird. I can't solve the issue without reproducing it. All the devices around me work as I expected them to work. Including emulator. I'll wait until somebody else face the same issue.

**Comment by GitStudying** [comment]
Okay, so I finally could test in on another phone. It is my Xiaomi Mi A1 with a qualcomm 625 processor and Android 11. The same exact problem occurs with your latest version. So I can't even believe I have now two devices both not particularly weird in any way that aren't working while all your devices do work.

**Comment by supersu-man** [comment]
If possible provide me with more info. And I might make one for PC using Python (kivymd) if atleast few more wanted it badly. I will try this again on phones around me. If possible send me logs, so I can figure out where is it going wrong.

**Comment by GitStudying** [comment]
This is on my Xiaomi mi A1, the first line is where you see I force stop to make sure it isn't already bugged:
`07-24 13:34:45.144 20583 20583 D AppButtonsPrefCtl: Stopping package com.supersuman.spd
07-24 13:34:45.147  1690  1705 I ActivityManager: Force stopping com.supersuman.spd appid=10191 user=0: from pid 20583
07-24 13:34:45.147  1690  1705 I ActivityManager: Killing 8086:com.supersuman.spd/u0a191 (adj 900): stop com.supersuman.spd due to from pid 20583
07-24 13:34:45.156 20583 20583 D AppButtonsPrefCtl: Sending broadcast to query restart status for com.supersuman.spd
07-24 13:34:45.247 20583 20583 D AppButtonsPrefCtl: Sending broadcast to query restart status for com.supersuman.spd
07-24 13:34:45.259 20583 20583 D AppButtonsPrefCtl: Sending broadcast to query restart status for com.supersuman.spd
07-24 13:34:45.341 20583 20583 D AppButtonsPrefCtl: Sending broadcast to query restart status for com.supersuman.spd
07-24 13:34:45.345 20583 20583 D AppButtonsPrefCtl: Got broadcast response: Restart status for com.supersuman.spd false
07-24 13:34:45.385 20583 20583 D AppButtonsPrefCtl: Got broadcast response: Restart status for com.supersuman.spd false
07-24 13:34:51.781  1690  1760 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.supersuman.spd/.MainActivity bnds=[36,622][288,888]} from uid 10144
07-24 13:34:51.810  1690  1717 I ActivityManager: Start proc 11961:com.supersuman.spd/u0a191 for pre-top-activity {com.supersuman.spd/com.supersuman.spd.MainActivity}
07-24 13:34:54.486 11961 11961 W RenderThread: type=1400 audit(0.0:526): avc: denied { read } for name="passwd" dev="dm-0" ino=6699 scontext=u:r:untrusted_app:s0:c191,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0 app=com.supersuman.spd
07-24 13:34:54.536  1690  1715 I ActivityTaskManager: Displayed com.supersuman.spd/.MainActivity: +2s748ms
07-24 13:35:10.455  1690  1777 D InputDispatcher: Waiting to send key to Window{bf9a382 u0 com.supersuman.spd/com.supersuman.spd.MainActivity} because there are unprocessed events that may cause focus to change
07-24 13:35:10.515  1690  1777 D InputDispatcher: Waiting to send key to Window{bf9a382 u0 com.supersuman.spd/com.supersuman.spd.MainActivity} because there are unprocessed events that may cause focus to change`

It seems to get stuck on that last line. There it is doing the behaviour already described earlier: First song name, 0% flashing error trying again in 3 seconds about every 5 to 10 seconds.

I will check if I can do the same for my other device.

**Comment by GitStudying** [comment]
My A41 gives the following logcat, it already starts when I focus one of the text inputs. The bufferQueues keep coming even after hitting download and then it gives the error retrying behaviour. The things inbetween happen when I switch focus so from the playlist link textinput to sub folder name input and then clicking download. It seems like it isn't finishing the buffer or something weird:
`07-25 12:56:29.099   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=8.55 dur=1052.31 max=480.66 min=9.92
07-25 12:56:30.101   807  2821 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=2.00 dur=1001.73 max=506.43 min=495.30
07-25 12:56:31.108   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=1.98 dur=1007.58 max=507.82 min=499.76
07-25 12:56:32.111   807  1237 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=1.99 dur=1002.83 max=510.78 min=492.05
07-25 12:56:33.384   807  2821 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=3.14 dur=1273.29 max=504.61 min=28.63
07-25 12:56:34.876   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=2.01 dur=1491.98 max=504.13 min=485.32
07-25 12:56:35.878   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=2.00 dur=1001.74 max=503.02 min=498.72
07-25 12:56:36.382 24959 24959 V InputMethodManager: Starting input: tba=com.supersuman.spd ic=com.android.internal.widget.EditableInputConnection@91477eb mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
07-25 12:56:36.390 24959 24959 D InputMethodManager: SSI - flag : 0 Pid : 24959 view : com.supersuman.spd
07-25 12:56:36.408 13110 13110 I AndroidIME: AbstractIme.onActivate():86 LatinIme.onActivate() : EditorInfo = Package = com.supersuman.spd : Type = Text : Learning = Enable : Suggestion = Show : AutoCorrection = Enable : Microphone = Show : NoPersonalizedLearning = Disable : AutoStartVoiceInput = Disable : AutoStartEmojiInput = Disable : SimulateDeviceLocked = False : imeActionName = NEXT : imeOptions = 8000005 : privateImeOptions = null, IncognitoMode = false, DeviceLocked = false
07-25 12:56:36.441 30284 30303 D WindowManager: showInsets: types=0x8, fromIme=true, win=Window{d9ff288 u0 com.supersuman.spd/com.supersuman.spd.MainActivity}, from=com.android.server.wm.ImeInsetsSourceProvider.lambda$scheduleShowImePostLayout$0$ImeInsetsSourceProvider:92 com.android.server.wm.-$$Lambda$ImeInsetsSourceProvider$1aCwANZDoNIzXR0mfeN2iV_k2Yo.run:2 com.android.server.wm.ImeInsetsSourceProvider.checkShowImePostLayout:121 com.android.server.wm.DisplayContent.applySurfaceChangesTransaction:4903 com.android.server.wm.RootWindowContainer.applySurfaceChangesTransaction:1290 com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace:1019 com.android.server.wm.RootWindowContainer.performSurfacePlacement:957 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:182 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:131 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:120
07-25 12:56:36.454 30284 30303 D WindowManager: showInsets: types=0x8, fromIme=true, win=Window{d9ff288 u0 com.supersuman.spd/com.supersuman.spd.MainActivity}, from=com.android.server.wm.ImeInsetsSourceProvider.lambda$scheduleShowImePostLayout$0$ImeInsetsSourceProvider:92 com.android.server.wm.-$$Lambda$ImeInsetsSourceProvider$1aCwANZDoNIzXR0mfeN2iV_k2Yo.run:2 com.android.server.wm.ImeInsetsSourceProvider.checkShowImePostLayout:121 com.android.server.wm.DisplayContent.applySurfaceChangesTransaction:4903 com.android.server.wm.RootWindowContainer.applySurfaceChangesTransaction:1290 com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace:1019 com.android.server.wm.RootWindowContainer.performSurfacePlacement:957 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:182 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:131 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:120
07-25 12:56:36.899   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=8.81 dur=1021.08 max=449.17 min=9.14
07-25 12:56:37.908   807  1237 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=1.98 dur=1008.90 max=505.87 min=503.03
07-25 12:56:38.767 30284 30284 D GameManagerService: identifyGamePackage. com.supersuman.spd, mCurrentUserId: 0, callerUserId: 0
07-25 12:56:38.768 30284 30284 D PkgDataHelper: getGamePkgData(). com.supersuman.spd
07-25 12:56:38.769 30284 30284 D GameManagerService: identifyGamePackage. com.supersuman.spd, mCurrentUserId: 0, callerUserId: 0
07-25 12:56:38.769 30284 30284 D PkgDataHelper: getGamePkgData(). com.supersuman.spd
07-25 12:56:39.309   807  1237 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=2.14 dur=1400.46 max=504.59 min=400.02
07-25 12:56:40.476   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=3.43 dur=1167.87 max=483.26 min=13.21
07-25 12:56:40.720 30284 30284 D GameManagerService: identifyGamePackage. com.supersuman.spd, mCurrentUserId: 0, callerUserId: 0
07-25 12:56:40.720 30284 30284 D PkgDataHelper: getGamePkgData(). com.supersuman.spd
07-25 12:56:40.721 30284 30284 D GameManagerService: identifyGamePackage. com.supersuman.spd, mCurrentUserId: 0, callerUserId: 0
07-25 12:56:40.721 30284 30284 D PkgDataHelper: getGamePkgData(). com.supersuman.spd
07-25 12:56:41.689   807   854 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=3.30 dur=1212.09 max=509.30 min=199.58
07-25 12:56:42.138 24959 24959 D InsetsSourceConsumer: setRequestedVisible: visible=false, type=13, host=com.supersuman.spd/com.supersuman.spd.MainActivity, from=android.view.InsetsSourceConsumer.hide:236 android.view.ImeInsetsSourceConsumer.hide:101 android.view.InsetsController.hideDirectly:1430 android.view.InsetsController.controlAnimationUnchecked:1112 android.view.InsetsController.applyAnimation:1417 android.view.InsetsController.hide:984 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6150 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 android.app.ActivityThread.main:8512
07-25 12:56:42.139 30284 32704 D InsetsSourceProvider: updateVisibility: serverVisible=true, clientVisible=false, source=InsetsSource: {mType=ITYPE_IME, mFrame=[0,1583][1080,2400], mVisible=false}, controlTarget=Window{d9ff288 u0 com.supersuman.spd/com.supersuman.spd.MainActivity}, from=com.android.server.wm.InsetsSourceProvider.setClientVisible:378 com.android.server.wm.InsetsSourceProvider.onInsetsModified:363 com.android.server.wm.InsetsStateController.onInsetsModified:416 com.android.server.wm.InsetsPolicy.onInsetsModified:320 com.android.server.wm.Session.insetsModified:512 android.view.IWindowSession$Stub.onTransact:1398 com.android.server.wm.Session.onTransact:145 android.os.Binder.execTransactInternal:1195 android.os.Binder.execTransact:1159 <bottom of call stack>
07-25 12:56:42.267   807   807 D SurfaceFlinger:      DEVICE | 0xb400006f6d508480 | 0002 | RGBA_8888    |    0.0    0.0 1080.0 2400.0 |    0    0 1080 2400 | com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0
07-25 12:56:42.638 30284 30302 D GameManagerService: identifyForegroundApp. com.supersuman.spd, mCurrentUserId: 0, callerUserId: 0
07-25 12:56:42.638 30284 30302 D PkgDataHelper: getGamePkgData(). com.supersuman.spd
07-25 12:56:43.114   807  2821 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=2.11 dur=1424.98 max=512.53 min=414.16
07-25 12:56:44.118   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=1.99 dur=1004.56 max=503.49 min=501.07
07-25 12:56:45.119   807  2821 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=2.00 dur=1001.00 max=501.52 min=499.48
07-25 12:56:46.138   807  2821 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=17.67 dur=1018.42 max=388.26 min=13.50
07-25 12:56:47.628   807  2821 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=2.01 dur=1490.26 max=505.44 min=483.51
07-25 12:56:48.629   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=5.00 dur=1000.87 max=500.81 min=13.08
07-25 12:56:49.641   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=1.97 dur=1012.70 max=506.95 min=505.75
07-25 12:56:50.646   807  1234 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=1.99 dur=1004.91 max=502.64 min=502.27
07-25 12:56:52.137   807  2821 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_24959#0](this:0xb400006f7150b658,id:15632,api:1,p:24959,c:807) queueBuffer: fps=2.01 dur=1490.63 max=506.43 min=484.58`

I hope you can use these logs to fix the issues.
As far as I can see the issue for my Samsung A41 and the Xiaomi Mi A1 seem to be different although could very well be related.
If you wish to see other info please tell me what you want me to do so I can help you.

**Comment by supersu-man** [comment]
Yes, finally able to reproduce the issue on my device. Check [this](https://github.com/supersu-man/SpotifyPlaylistDownloader/releases/tag/v1.2) new update and let me know if this works for you. This has to work. Tested on mine.

**Comment by GitStudying** [comment]
This worked flawlessly, until my 19th song apparently. It does get stuck again with the retrying error, 
and ADB:
08-07 20:50:56.922   807   856 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_25336#0](this:0xb40000735a745c58,id:682,api:1,p:25336,c:807) queueBuffer: fps=4.98 dur=1004.39 max=505.39 min=17.00
08-07 20:50:57.932   807   856 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_25336#0](this:0xb40000735a745c58,id:682,api:1,p:25336,c:807) queueBuffer: fps=2.97 dur=1009.70 max=508.11 min=167.05
08-07 20:50:59.420   807   856 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_25336#0](this:0xb40000735a745c58,id:682,api:1,p:25336,c:807) queueBuffer: fps=4.70 dur=1488.65 max=503.06 min=19.32
08-07 20:51:00.425   807   856 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_25336#0](this:0xb40000735a745c58,id:682,api:1,p:25336,c:807) queueBuffer: fps=4.98 dur=1004.59 max=504.77 min=19.25
08-07 20:51:01.430   807   856 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_25336#0](this:0xb40000735a745c58,id:682,api:1,p:25336,c:807) queueBuffer: fps=4.97 dur=1005.27 max=505.84 min=20.19
08-07 20:51:02.434   807  2429 I BufferQueueProducer: [com.supersuman.spd/com.supersuman.spd.MainActivity$_25336#0](this:0xb40000735a745c58,id:682,api:1,p:25336,c:807) queueBuffer: fps=7.97 dur=1004.16 max=336.56 min=12.70

**Comment by supersu-man** [comment]
The flashes will be removed in future updates. The problem occurs in [this](https://yt1s.com/en/1-youtube-mp3) api where it doesnt not respond sometimes which returns null value. Letting it retry for few seconds will download the song. Also sometimes searching songs could get wrong results from Youtube, which also will be improved in future updates.
