### ISSUE TITLE
Having difficulties using the app

### ISSUE THREAD

**Issue by Skarmi** [supersu-man/SpotifyPlaylistDownloader#4]
Bro could u pls help me ...
I am unable to download any songs on my phone 
What do I need to do with the subfolder ?
And whats the slider that goes till 30 ?

**Comment by Skarmi** [comment]
Like are their any videos on how to use the app ?

**Comment by supersu-man** [comment]
> Bro could u pls help me ...
> I am unable to download any songs on my phone 
> What do I need to do with the subfolder ?
> And whats the slider that goes till 30 ?

Alright, firstly the permissions to let the app the download songs, then the slider is the maximum number of retries before skipping the song to next one, subfolder Is just a folder inside downloads/spd where the songs from this playlist are going to download. And then the playlist link which is your Spotify playlist link, make sure that playlist is not private before pasting the link. For now the download process doesnt happen in the background, app need to be kept open.

**Comment by Skarmi** [comment]
Thanks for quick reply ... <3
