### ISSUE TITLE
App keeps closing after I downloaded the app.

### ISSUE THREAD

**Issue by Ravier109283** [supersu-man/SpotifyPlaylistDownloader#6]
I downloaded the app and tried to launch it but it wont open, it just instantly crashes after launching.

**Comment by supersu-man** [comment]
> I downloaded the app and tried to launch it but it wont open, it just instantly crashes after launching.

Known issue, will be fixing today. Stay tuned for new update

**Comment by supersu-man** [comment]
Fixed with [this release](https://github.com/supersu-man/SpotifyPlaylistDownloader/releases/tag/v1.6)
